server:
  port: 8761
spring:
  application:
    name: naming-server
eureka:
  client:
    # desabilitar para que as instancias do eureka não se auto-registrem (em ambiente de produção é melhor retirar esta configuração)
    register-with-eureka: false
    fetch-registry: false

