server:
  port: 8888
spring:
  application:
    name: microsservice_configure_server
  profiles:
    active:
    - native
   # integrando spring cloud com o github
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JoseLuiz18Bd/microservice_config_server
          #username: user_name
          #password: password
          default-label: main
          search-paths:
          - 'greeting-service*'
          
          